api_platform:    
    enable_docs: true #Poner en false para producción
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header        
    collection:
        pagination:
            items_per_page: 10 # Default value  
      