@AuthorizationToken = {{token}}
@baseUrl = {{host}}

@id = 1

### OBTENER ARCHIVO
GET {{baseUrl}}/compartidos HTTP/1.1
Authorization: {{AuthorizationToken}}

### OBTENER ARCHIVO
GET {{baseUrl}}/compartidos/{{id}} HTTP/1.1
Authorization: {{AuthorizationToken}}
