@AuthorizationToken = {{token}}
@baseUrl = {{host}}

@id = 1

### OBTENER ARCHIVO
GET {{baseUrl}}/estado_flujos HTTP/1.1
Authorization: {{AuthorizationToken}}

### OBTENER ARCHIVO
GET {{baseUrl}}/archivos/{{id}} HTTP/1.1
Authorization: {{AuthorizationToken}}

### DESCARGAR ARCHIVO
GET {{baseUrl}}/archivos/{{id}}/download HTTP/1.1
Authorization: {{AuthorizationToken}}


### OBTENER ARCHIVOS CON FILTROS
GET {{baseUrl}}/archivos HTTP/1.1
  ?query=
  &order[nombre]=asc
  &page=1 
Authorization: {{AuthorizationToken}}
