@AuthorizationToken = {{token}}
@baseUrl = {{host}}

@id = 1

### OBTENER REGISTROS DE TIPO ENTIDAD
GET {{baseUrl}}/registro_texto_largos HTTP/1.1
Authorization: {{AuthorizationToken}}

### OBTENER REGISTRO DE TIPO ENTIDAD
GET {{baseUrl}}/registro_texto_largos/{{id}} HTTP/1.1
Authorization: {{AuthorizationToken}}

