@AuthorizationToken = {{token}}
@baseUrl = {{host}}

@id = 1

### OBTENER REGISTROS DE TIPO ENTIDAD
GET {{baseUrl}}/registro_numerico_decimals HTTP/1.1
Authorization: {{AuthorizationToken}}

### OBTENER REGISTRO DE TIPO ENTIDAD
GET {{baseUrl}}/registro_numerico_decimals/{{id}} HTTP/1.1
Authorization: {{AuthorizationToken}}

