version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '5306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf

  php:
    container_name: php
    build:
      context: ./php
    ports:
      #fastcgi port served to nginx
      - '9000:9000'
    volumes:
      - ./back:/var/www/symfony_docker
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./back:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

