<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2019-07-23 03:55:15.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use App\Controller\ExecuteCustomMasterQuery;
use App\Controller\ExportCustomMasterQuery;
use App\Controller\ExecuteMasterQuery;
use App\Controller\ExportMasterQuery;
use App\Filter\ORSearchFilter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource(
 *    collectionOperations={
 *      "get"={"method"="GET"},
 *      "post"={"method"="POST"},
 *      "executecustomquery"={
 *          "method"="POST",
 *          "path"="/consulta_maestras_version/execute/customquery",
 *          "controller"=ExecuteCustomMasterQuery::class,
 *              "defaults"={
 *                      "_items_per_page"=10
 *              }
 *          },
 *      "exportcustomquery"={
 *          "method"="POST",
 *          "path"="/consulta_maestras_version/export/customquery",
 *          "controller"=ExportCustomMasterQuery::class,
 *              "defaults"={
 *                      "_items_per_page"=10
 *              }
 *       },
 *       "execute"={
 *          "method"="GET",
 *          "path"="/consulta_maestras_version/{id}/execute",
 *          "controller"=ExecuteMasterQuery::class,
 *              "defaults"={
 *                      "_items_per_page"=10
 *              }
 *       },
 *      "export"={
 *          "method"="GET",
 *          "path"="/consulta_maestras_version/{id}/export",
 *          "controller"=ExportMasterQuery::class,
 *              "defaults"={
 *                      "_items_per_page"=10
 *              }
 *          }
 *    },
 *   itemOperations={
 *      "put",
 *      "get"={
 *         "method"="GET",
 *         "path"="/consulta_maestras_version/{id}",
 *          "requirements"={"id"="\d+"}
 *        }
 *  }
 * )
 * @ApiFilter(
 *      ORSearchFilter::class,
 *      properties={"nombre","detalle"}
 * )
 *
 * @ApiFilter(
 *      OrderFilter::class,
 *      properties={"nombre","detalle"},
 *      arguments={"orderParameterName"="order"})
 *
 * App\Entity\ConsultaMaestraVersion
 *
 * @ORM\Entity()
 * @ORM\Table(name="consulta_maestra_version", indexes={@ORM\Index(name="fk_consulta_maestra_version_formulario_version_idx", columns={"formulario_version_id"})})
 */
class ConsultaMaestraVersion
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="text")
     */
    protected $detalle;

    /**
     * @ORM\Column(type="integer")
     */
    protected $estado_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $formulario_version_id;

    /**
     * @ORM\ManyToOne(targetEntity="FormularioVersion", inversedBy="consultasMaestrasVersion")
     * @ORM\JoinColumn(name="formulario_version_id", referencedColumnName="id", nullable=false)
     */
    protected $formularioVersion;

    /**
     * @ORM\ManyToMany(targetEntity="Grupo", inversedBy="consultasMaestrasVersion")
     * @ORM\JoinTable(name="consulta_maestra_version_grupo",
     *     joinColumns={@ORM\JoinColumn(name="consulta_maestra_version_id", referencedColumnName="id", nullable=false)},
     *     inverseJoinColumns={@ORM\JoinColumn(name="grupo_id", referencedColumnName="id", nullable=false)}
     * )
     */
    protected $grupos;

    /**
     * @ORM\ManyToMany(targetEntity="Rol", mappedBy="consultasMaestrasVersion")
     */
    protected $rols;

    public function __construct()
    {
        $this->grupos = new ArrayCollection();
        $this->rols = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\ConsultaMaestra
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \App\Entity\ConsultaMaestra
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of detalle.
     *
     * @param string $detalle
     * @return \App\Entity\ConsultaMaestra
     */
    public function setDetalle($detalle)
    {
        $this->detalle = $detalle;

        return $this;
    }

    /**
     * Get the value of detalle.
     *
     * @return string
     */
    public function getDetalle()
    {
        return $this->detalle;
    }

    /**
     * Set the value of estado_id.
     *
     * @param integer $estado_id
     * @return \App\Entity\ConsultaMaestra
     */
    public function setEstadoId($estado_id)
    {
        $this->estado_id = $estado_id;

        return $this;
    }

    /**
     * Get the value of estado_id.
     *
     * @return integer
     */
    public function getEstadoId()
    {
        return $this->estado_id;
    }

    /**
     * Set the value of formulario_version_id.
     *
     * @param integer $formulario_version_id
     * @return \App\Entity\ConsultaMaestra
     */
    public function setFormularioVersionId($formulario_version_id)
    {
        $this->formulario_version_id = $formulario_version_id;

        return $this;
    }

    /**
     * Get the value of formulario_version_id.
     *
     * @return integer
     */
    public function getFormularioVersionId()
    {
        return $this->formulario_version_id;
    }

    /**
     * Set FormularioVersion entity (many to one).
     *
     * @param \App\Entity\FormularioVersion $formularioVersion
     * @return \App\Entity\ConsultaMaestra
     */
    public function setFormularioVersion(FormularioVersion $formularioVersion = null)
    {
        $this->formularioVersion = $formularioVersion;

        return $this;
    }

    /**
     * Get FormularioVersion entity (many to one).
     *
     * @return \App\Entity\FormularioVersion
     */
    public function getFormularioVersion()
    {
        return $this->formularioVersion;
    }

    /**
     * Add Grupo entity to collection.
     *
     * @param \App\Entity\Grupo $grupo
     * @return \App\Entity\ConsultaMaestra
     */
    public function addGrupo(Grupo $grupo)
    {
        $this->grupos[] = $grupo;
        $grupo->addConsultaMaestra($this);

        return $this;
    }

    /**
     * Remove Grupo entity from collection.
     *
     * @param \App\Entity\Grupo $grupo
     * @return \App\Entity\ConsultaMaestra
     */
    public function removeGrupo(Grupo $grupo)
    {
        $grupo->removeConsultaMaestra($this);
        $this->grupos->removeElement($grupo);

        return $this;
    }

    /**
     * Get Grupo entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGrupos()
    {
        return $this->grupos;
    }

    /**
     * Add Rol entity to collection.
     *
     * @param \App\Entity\Rol $rol
     * @return \App\Entity\ConsultaMaestra
     */
    public function addRol(Rol $rol)
    {
        $this->rols[] = $rol;

        return $this;
    }

    /**
     * Remove Rol entity from collection.
     *
     * @param \App\Entity\Rol $rol
     * @return \App\Entity\ConsultaMaestra
     */
    public function removeRol(Rol $rol)
    {
        $this->rols->removeElement($rol);

        return $this;
    }

    /**
     * Get Rol entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRols()
    {
        return $this->rols;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'detalle', 'estado_id', 'formulario_version_id');
    }
}
