<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2019-11-22 14:53:56.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource(
 *    collectionOperations={
 *      "get"={"method"="GET"},
 *      "post"={"method"="POST"}
 *    },
 *   itemOperations={
 *      "put",
 *      "get"={
 *         "method"="GET",
 *         "path"="/permites/{id}",
 *          "requirements"={"id"="\d+"}
 *        }
 *  }
 * )
 * App\Entity\Permite
 *
 * @ORM\Entity()
 * @ORM\Table(name="permite")
 */
class Permite
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $peso;    

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected $acciones;

    /**
     * @ORM\OneToMany(targetEntity="OpcionFormulario", mappedBy="permite")
     * @ORM\JoinColumn(name="id", referencedColumnName="permite_id", nullable=false)
     */
    protected $opcionFormularios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $orden; 


    public function __construct()
    {
        $this->opcionFormularios = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\Permite
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \App\Entity\Permite
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of peso.
     *
     * @param integer $peso
     * @return \App\Entity\Permite
     */
    public function setPeso($peso)
    {
        $this->peso = $peso;

        return $this;
    }

    /**
     * Get the value of peso.
     *
     * @return integer
     */
    public function getPeso()
    {
        return $this->peso;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \App\Entity\Permite
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $acciones
     * @return \App\Entity\Permite
     */
    public function setAcciones($acciones)
    {
        $this->nombre = $acciones;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getAcciones()
    {
        return $this->acciones;
    }

    /**
     * Add OpcionFormulario entity to collection (one to many).
     *
     * @param \App\Entity\OpcionFormulario $opcionFormulario
     * @return \App\Entity\Permite
     */
    public function addOpcionFormulario(OpcionFormulario $opcionFormulario)
    {
        $this->opcionFormularios[] = $opcionFormulario;

        return $this;
    }

    /**
     * Remove OpcionFormulario entity from collection (one to many).
     *
     * @param \App\Entity\OpcionFormulario $opcionFormulario
     * @return \App\Entity\Permite
     */
    public function removeOpcionFormulario(OpcionFormulario $opcionFormulario)
    {
        $this->opcionFormularios->removeElement($opcionFormulario);

        return $this;
    }

    /**
     * Get OpcionFormulario entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOpcionFormularios()
    {
        return $this->opcionFormularios;
    }

    /**
     * Add OpcionFormularioVersion entity to collection (one to many).
     *
     * @param \App\Entity\OpcionFormularioVersion $opcionFormulario
     * @return \App\Entity\Permite
     */
    public function addOpcionFormularioVersion(OpcionFormularioVersion $opcionFormularioVersion)
    {
        $this->opcionFormulariosVersion[] = $opcionFormularioVersion;

        return $this;
    }

    /**
     * Remove OpcionFormularioVersion entity from collection (one to many).
     *
     * @param \App\Entity\OpcionFormularioVersion $opcionFormularioVersion
     * @return \App\Entity\Permite
     */
    public function removeOpcionFormularioVersion(OpcionFormularioVersion $opcionFormularioVersion)
    {
        $this->opcionFormulariosVersion->removeElement($opcionFormularioVersion);

        return $this;
    }

    /**
     * Get OpcionFormularioVersion entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOpcionFormulariosVersion()
    {
        return $this->opcionFormulariosVersion;
    }

     /**
     * Set the value of orden.
     *
     * @param integer $orden
     * @return \App\Entity\Permite
     */
    public function setOrden($orden)
    {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get the value of orden.
     *
     * @return integer
     */
    public function getOrden()
    {
        return $this->orden;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'acciones', 'orden');
    }
}
